name: Python Tests

on:
  push:
    branches: [ "main" ]  # Déclenchement uniquement sur la branche main
  pull_request:
    branches: [ "main" ]  # Déclenchement uniquement sur la branche main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Si tu as un fichier requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests/tests.py  # Lancer les tests avec unittest
