name: Python Tests

on:
  push:
    branches:
      - tests-unitaires   # Change par ta branche (ex: `main` ou `tests-unitaires`)
  pull_request:
    branches:
      - tests-unitaires   # Change par ta branche (ex: `main` ou `tests-unitaires`)

jobs:
  test:
    runs-on: ubuntu-latest  # Le système d'exploitation utilisé par GitHub Actions

    steps:
    # Étape 1 : Vérifier et cloner le code
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Utilise la version de Python que tu préfères

    # Étape 3 : Installer les dépendances depuis `requirements.txt` (si nécessaire)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tu as un fichier `requirements.txt`

    # Étape 4 : Exécuter les tests avec `unittest` ou `pytest`
    - name: Run tests with unittest
      run: |
        python -m unittest discover -s tests   # Si tu utilises unittest pour tes tests

    # Si tu préfères utiliser `pytest`, remplace l'étape ci-dessus par celle-ci :
    # - name: Run tests with pytest
    #   run: |
    #     pip install pytest
    #     pytest tests/tests.py  # Remplace ce chemin par le bon chemin de ton fichier de tests
